<?php

function youtube_activity_permission() {
  return array(
    'administer youtube activity' => array(
      'title' => t('Administer youtube activity'),
      'description' => t('Perform administration tasks for youtube activity.'),
    ),
  );
}


function youtube_activity_menu() {
  $items["admin/structure/youtube_activity"] = array(
    'title' => 'Yotube parameters',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('youtube_activity_form',),
    'access arguments' => array('administer youtube activity'),
  );
$items["retrieve_youtube_activity"] = array(
    'title' => 'Yotube parameters',
    'page callback' => 'retrieve_youtube_activity',
    'page arguments' => array(),
    'access arguments' => array('administer youtube activity'),
  );



  return $items;
}

function youtube_activity_form(){
    $form['you_api_key'] = array(
      '#type' => 'textfield', 
      '#title' => t('API KEY'), 
      '#default_value' => variable_get('you_api_key',''), 
      '#description' => "get from https://console.developers.google.com", 
      '#size' => 60, 
      '#maxlength' => 255, 
      '#required' => TRUE,

    );
    $form['you_channel_id'] = array(
      '#type' => 'textfield', 
      '#title' => t('Chanel IDs'), 
      '#default_value' => variable_get('you_channel_id',''), 
      '#description' => "comma separated", 
      '#size' => 60, 
      '#maxlength' => 255, 
      '#required' => TRUE,

    );

    $form['you_max_retrieve_data'] = array(
      '#type' => 'textfield', 
      '#title' => t('Max retrieve data'), 
      '#default_value' => variable_get('you_max_retrieve_data','50'), 
      '#size' => 60, 
      '#maxlength' => 255, 
      '#required' => TRUE,

    );

  return system_settings_form($form);
}
function retrieve_youtube_activity(){
    $data=array('key'=> variable_get('you_api_key',''),'part'=>'snippet,id,contentDetails','maxResults'=>variable_get('you_max_retrieve_data','50'));
    if($channel=variable_get('you_channel_id',false))$data['channelId']=$channel;
    if(strpos($channel, ',')){
      $channels=explode(',', $channel);
      foreach ($channels as $channel) {
        $data['channelId']=$channel;
        _get_ytb_data($data);
      }



    } else {
      _get_ytb_data($data);
    }

  

}

function _get_ytb_data($data){
  $full_url = url('https://www.googleapis.com/youtube/v3/activities', array('query' => $data));
    $result = drupal_http_request($full_url);
    $result_set=json_decode($result->data);
    foreach ($result_set->items as $key => $item) {
        db_merge('activities')
      ->key(array('id' => $item->contentDetails->upload->videoId))
      ->fields(array(
            'id' => $item->contentDetails->upload->videoId,
            'type' => $item->snippet->type,
            'title' => $item->snippet->title,
            'description' => $item->snippet->description,
            'type' => $item->snippet->type,
            'channelId' => $item->snippet->channelId,
            'json' => json_encode($item),
            'publishedAt' => strtotime($item->snippet->publishedAt),
            'status' => 1,
            'transaction_time' => time()
      ))
      ->execute();
    }


}
function youtube_activity_cron(){
  retrieve_youtube_activity();  
}
function youtube_activity_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'youtube_activity') . '/views',
  );
}

